export const SET_CONTACTS = 'SET_CONTACTS'
export const SET_CONTACTS_ERROR = 'SET_CONTACTS_ERROR'
export const SET_CONTACTS_LOADING = 'SET_CONTACTS_LOADING'

export const SET_ABOUT = 'SET_ABOUT'
export const SET_ABOUT_LOADING = 'SET_ABOUT_LOADING'
export const SET_ABOUT_ERROR = 'SET_ABOUT_ERROR'
